### ISSUE TITLE
[bug]: Updater doesn't work when built through Tauri Action

### ISSUE THREAD

**Issue by spectraldoy** [tauri-apps/tauri-action#445]
I raised this issue in the https://github.com/tauri-apps/tauri repository as I initially thought it might be an issue with the updater code. However, I'm raising it here as well as I realize that it could very well be an issue with the Tauri action instead. Extensive details can be found here: https://github.com/tauri-apps/tauri/issues/6821

Let me know if anyone needs more information, if I should take down the issue in either of these repositories, or if you know what I'm doing wrong and how I can fix it.

Thank you.

**Comment by FabianLars** [comment]
Hmm, this sounds more like a config issue to be honest. At least i'm not aware of any general problems.

First of all, to debug the default dialog's updater events you can modify your main function to look more like this:
```rs
fn main() {
  let app = tauri::Builder::default()
    .invoke_handler(tauri::generate_handler![])
    .build(tauri::generate_context!()) //notice build instead of run
    .expect("error preparing tauri app");
  app.run(|_app_handle, event| {
    if let tauri::RunEvent::Updater(event) = event {
      dbg!(event);
    }
  });
}
```
Then if you start the app from within a terminal it will print the events.

A few general things:
1) The updater endpoint must point to the latest release (either by hardcoding it, or using the `latest` url)
2) The downloaded file must have a lower version than the one the one behind the endpoint url
3) The private and public keys must be configured correctly (via gh secrets and env vars in the workflow)

**Comment by spectraldoy** [comment]
I am certain that the updater endpoint is hardcoded to the `releases/latest/download/latest.json` from my app repository.  I am also certain that the version of the app I'm testing the updater with has a lower version than the one released. I also think that my private and public keys are properly configured in gh secrets and env vars.

Thank you for letting me know about the debugging syntax. I'll try that and get back to you.

**Comment by spectraldoy** [comment]
Sorry, just wanted to ask how do I run the app from the command line? If I use `tauri dev` it doesn't seem to be printing anything in the terminal even when the updater dialog shows up. If I use `tauri build --debug` or `tauri build`, I don't have a terminal at which to see things printed.

I don't know if this is another problem, but if I try to run the executable directly from the terminal, i.e. if I execute /Applications/TauriApp.app/Contents/MacOS/TauriApp then I first, get a segmentation fault (it seems to have tried to access memory at byte 0), which opens up an error screen that gives me a stack trace and an option to reopen the app. Reopening the app works perfectly fine, and the updater dialog also works perfectly fine.

How exactly was I supposed to run the app from the command line to see the updater events printed out?

Thank you.

**Comment by spectraldoy** [comment]
@FabianLars I think I might have found the issue. I've been compiling and releasing debug versions so that if my users find bugs, it'll be easier to figure out what's causing them from their machines. I just released two release builds through GitHub Actions, rather than debug builds, and I downloaded the first one to check if the updater worked. It did.

I don't think it should be expected behavior for the updater not to work when the the debug version of the app is built. Can you confirm whether or not this is a known issue, or expected behavior?

Thank you.

Edit:
Confirmed on both MacOS and Windows machines that with the release version, the updater works, but not with the debug version.

**Comment by FabianLars** [comment]
I'm pretty sure the debug version (not dev) should work too, can you check how the updater.json file looks like when building debug versions? Does it still contain the correct fields?

I'll also do some testing my own tomorrow, so don't worry if you can't check it :)

Edit: Just noticed your release repo and the debug file indeed looks correct to me...

**Comment by spectraldoy** [comment]
Thank you very much for looking into my repo. Just confirming both that you were looking at this repo: https://github.com/StackBaker/app-releases and that you meant the latest.json file, not the debug file? Or did you mean something different by debug file.

**Comment by FabianLars** [comment]
Yep, that's the repo, and yes i meant the latest.json file, sorry about that typo.

**Comment by spectraldoy** [comment]
Sorry to keep sending messages, but here's my `tauri.conf.json` in case this helps (I've omitted the pubkey here but I'm sure that's correct as well):

```json
{
  "build": {
    "beforeDevCommand": "pnpm dev",
    "beforeBuildCommand": "pnpm build",
    "devPath": "http://localhost:1420",
    "distDir": "../dist",
    "withGlobalTauri": false
  },
  "package": {
    "productName": "StackBaker",
    "version": "0.1.0"
  },
  "tauri": {
    "allowlist": {
      "all": false,
      "shell": {
        "all": false,
        "open": true
      }
    },
    "bundle": {
      "active": true,
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.stackbaker.dev",
      "targets": "all",
      "category": "Productivity"
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": true,
      "endpoints": [
        "https://github.com/StackBaker/app-releases/releases/latest/download/latest.json"
      ],
      "dialog": true,
      "pubkey": "***"
    },
    "windows": [
      {
        "fullscreen": false,
        "resizable": true,
        "title": "StackBaker",
        "width": 1366,
        "height": 768
      }
    ]
  }
}
```

**Comment by spectraldoy** [comment]
I sincerely apologize, I just looked at my commit from the debug version that I had released with which I was testing the updater. The updater endpoint URL was incorrect in that. I just released 2 new debug versions and tested whether the updater works, and it does.

Thank you so much for looking into this, and I apologize again for raising this issue without properly looking for my own errors.

**Comment by FabianLars** [comment]
Glad you figured it out! And don't worry about it, updater issues are still pretty hard to debug :)
